spring:
  application:
    name: cqrs
  datasource:
    url: jdbc:postgresql://localhost:5432/query_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/admin
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cqrs
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: cqrs
  cache:
    type: redis

